"""pre-phase5: per-user access, token limits, priority

Revision ID: 58032fc261ef
Revises: 01d692d2e30b
Create Date: 2026-07-17 14:20:36.860894

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '58032fc261ef'
down_revision: Union[str, Sequence[str], None] = '01d692d2e30b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # server_default backfills the existing rows; the ORM default handles new rows.
    with op.batch_alter_table('plans', schema=None) as batch_op:
        batch_op.add_column(sa.Column('daily_token_limit', sa.Integer(), nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('monthly_token_limit', sa.Integer(), nullable=False, server_default='0'))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('must_change_password', sa.Boolean(), nullable=False, server_default=sa.false()))
        batch_op.add_column(sa.Column('allowed_models', sa.JSON(), nullable=False, server_default='[]'))
        batch_op.add_column(sa.Column('model_priority', sa.JSON(), nullable=False, server_default='[]'))
        batch_op.add_column(sa.Column('daily_call_limit', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('monthly_call_limit', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('daily_token_limit', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('monthly_token_limit', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('monthly_token_limit')
        batch_op.drop_column('daily_token_limit')
        batch_op.drop_column('monthly_call_limit')
        batch_op.drop_column('daily_call_limit')
        batch_op.drop_column('model_priority')
        batch_op.drop_column('allowed_models')
        batch_op.drop_column('must_change_password')

    with op.batch_alter_table('plans', schema=None) as batch_op:
        batch_op.drop_column('monthly_token_limit')
        batch_op.drop_column('daily_token_limit')

    # ### end Alembic commands ###
